<?php

return [
    "page_title" => "Terms and Conditions",
    "title" => "Terms and Conditions",
    "intro" => "I, the undersigned, hereby acknowledge and declare with my full legal capacity and free will the following:",
    "clauses" => [
        1 => "That all information and data I have submitted to Al-Ibdaa Microfinance Company (Closed LLC), Commercial Registration No. (1-72533), in order to obtain financing for the amount specified above - including particularly personal data, contact information, employment, workplace, monthly salary from my job and/or any other income - is correct and represents reality without any distortion or alteration contrary to truth and reality. If it is found that I have provided incorrect information and/or concealed data and/or information about my true financial situation from Al-Ibdaa Microfinance Company (Closed LLC), I shall be considered as having submitted incorrect and misleading information in bad faith, committing the crime of forgery, and I shall bear criminal and civil liability. In this case, the company has the right to take all legal measures against me in accordance with Article (270) and Article (271/2) of the Penal Code.",
        2 => "I acknowledge that the company has the right \"in all cases\" to approve the financing request as is, reduce its value, or reject the financing request without me having any right to object. The company also has the right (according to its absolute discretion) to grant me a grace period to begin repayment of the financing or reject this, and I have no right whatsoever to object to this.",
        3 => "I authorize Al-Ibdaa Microfinance Company to inquire about my credit record with \"Benefit\" company on the following dates:",
        4 => "I authorize the company to verify the accuracy of the information provided in this application from any source without me having the right to object to this regarding the company and/or any other party. I waive banking confidentiality in this regard. This authorization includes inquiries about me from \"Watheq\" and/or any security, governmental, civil, or private entity. I also allow the company's employees or those they authorize to visit me at my home and/or workplace and/or project at any time before granting the financing, during its validity, and/or afterward.",
        5 => "I agree to pay a non-refundable application fee even if the request is rejected, in addition to administrative fees, processing fees, notary fees/charges, and/or any other fees the company decides to add to the financing at any time, which I will pay to the company in advance immediately upon disbursement of the financing to me via a check issued by the company or via direct transfer to my bank account as specified in the application above. I also acknowledge that in case of early repayment, the administrative fees, processing fees, and/or notary fees/charges, and/or any other fees of any kind that I paid in advance are non-refundable regardless of how close the early repayment date is to the financing disbursement date.",
        6 => "I agree that I have no right to demand the return of any documents related to this application, even if the financing request is rejected (whether they are originals or copies).",
        7 => "In case of approval of the financing, I agree to comply with all the company's policies and procedures, including timely repayment and no early repayment, and to pay delay penalties of (6) Bahraini dinars for each day of delay in paying any installment of the financing as scheduled by the company.",
        8 => "I acknowledge - in case of wishing to obtain any services from the company related to this financing - that I will pay the fees determined by the company (published in its branches and on its website clearly) without any objection, in addition to any taxes and/or fees imposed by official entities of any kind.",
        9 => "I grant Al-Ibdaa Microfinance Company and/or its subsidiaries and/or cooperating institutions and/or entities it owns the right to use the information and documents I submitted with this application in any marketing and/or promotional materials for the company's activities and/or those institutions and entities even after the financing ends and all installments are paid. I also grant the company the right to obtain photos of me and/or the project for use in marketing and promoting the company's activities and/or those institutions and entities. I acknowledge that the company and/or those institutions and entities have the right to continue using those photos, data, and success stories in any marketing, advertising, documentary materials, or any other means without time limitation, whether before, during, or after the end of this loan.",
        10 => "I grant Al-Ibdaa Microfinance Company the right to provide any official or private entity, whether local or foreign, with any information contained in this application. I specifically mention the company's absolute right to provide \"Benefit\" and/or \"Watheq\" and/or any governmental, semi-governmental, cooperating, financing, or other entities with such information, and I bear any consequences if it turns out that this information is untrue and/or conflicts with information available to those entities."
    ],
    "conclusion" => "The undersigned acknowledge having read and understood all the above terms and conditions, and their signature below shall be considered as a final, irrevocable acknowledgment that cannot be challenged or revoked in the future."
];